AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketName:
    Description: The name of the bucket used to store CloudFormation templates
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: BucketOwnerFullControl
